### ISSUE TITLE
Magbot

### ISSUE THREAD

**Issue by Netlob** [mamorgen/magbot3#6]

**Comment by tamarpostma** [comment]
Hi again guys, Same problem again.. Account is blocked, so deleted it (magbot.nl) and now can't register again. Any news on Beta.magbot.nl?

**Comment by Sj3rd** [comment]
Oopsie, we still had the project on freeze due to other more important projects. We'll try to launch tonight or perhaps tomorrow.

Thanks for waiting patiently and reminding!

**Comment by tamarpostma** [comment]
No need to apologize! We should just  be glad someone makes this stuff for free..😎

Verstuurd vanaf mijn iPhone

**Comment by tamarpostma** [comment]
Hi again,

It looks like it’s all up and running! 
I now realise what it was you’re asking me a while back about how I would want to see the time slot.
Right now all I am seeing is ‘English van T.Postma’ - I do not, however, see the class I have as it was in the old magbot.
Is there a way to turn this on?

Thanks again! And I like that there is only one calendar instead of 4…

**Comment by Sj3rd** [comment]
If you want we can add the class for teacher accounts. 

Haha great to hear that you like there's only 1 calendar, we had some differences of opinion with that one (haha I won @7kasper ), so we decided you could choose what you prefer.

Is this something what would satisfy you:
![image](https://user-images.githubusercontent.com/33723199/53686367-5542bf00-3d26-11e9-97b7-c0fbe3666fed.png)
Or without the 1 -?
Please give an example so we can try to make that the standard for teacher accounts :)

**Comment by tamarpostma** [comment]
Yes! This would be great….LOL! What an honour…

And definitely 1 calendar is the best improvement ever! Because it’s much more tidy… ;)
The '1 - 4H6 English' option is perfect, and the 1- is very much necessary because then I know what lesson period it is….
If you want me to test other stuff I am very willing to do so!

**Comment by 7kasper** [comment]
We are currently merging the old magbot users into the new system 🔢 
Because we need to switch the google client so the other 280 users don't have to re-register, it does mean @tamarpostma that you need to re-register one more time on the new site once it is up and running (you will be notified). When re-registering in a day or so, you can uncheck the simple summary (`Laat een versimpelde versie van je afspraak zien, bijvoorbeeld: "Nederlands"`) box allowing you to again see the classes that you have to give like in the old magbot.

I didn't even know that teacher accounts could work in the first place and I'm very glad it does since I have had people asking me about it from time to time. So, let us also take you up on your offer. I don't have things to test specifically yet, but it is very useful for us if you keep reporting any issues / suggestions you have with magbot. Since you have both a teacher and a parent account you are the perfect tester we could ask for 😄

**Comment by tamarpostma** [comment]
Hi guys,

Perfect! No problem re-registering, I know exactly how it works now  ;)
Ok, great. So, you guys are really doing the switch today. Great to hear. Just out a matter of curiosity, why are you doing all this work? I thought perhaps as ex-pupils maybe you thought it was so irritating there was no Magister agenda (which is also my annoyance) and decided to build the link. Could you not charge a fee or a donation or 1 time payment? I would be willing to do so, because I really don’t understand why this functionality is still not in Magister.

Ok, so the class names are back? That’s good. 
I am quite happy to test as a teacher, parent, and of course I can log in using my kids' accounts and test that too. 

A few questions about future implementation (which you can of course just ignore  😄)
Is a two-way sync  out of the question? Probably since Magister would need to participate in that, but wouldn’t that be great.
Also, another thing I was wondering. At our school our schedule gets read-in only 5 or 6 weeks at a time. So if a test is scheduled after that, I add it manually.
It would be great If I could (as a teacher) add those tests and other personal appointments to Magister and then see those in Magbot calendar.At the moment they do not show up in the Magbot calendar. Is this an inaccessible part of the system? I can send you a screenshot if you want to know what I mean. 

Ok, great work and looking forward to testing anytime…

Tamar

**Comment by Sj3rd** [comment]
Goed om te horen allemaal. Een two-way sync is volgensmij mogelijk, en lijkt me een leuk project waar ik aan kan werken als Magbot3.1 gereleased is.

Mmmm, dat van die toetsen.... Zou kunnen, heb daar wel een idee voor.
@7kasper voor jouw: we kunnen ipv komende 2 weken komende 6 weken ofzo doen, en dan de specials er vast in zetten.

Donaties zijn natuurlijk welkom ;), ik betaal namelijk elke maand voor serverkosten. Het programmeren ervan is alleen maar hobby en kennis vergroten.

Mvg Sjoerd

**Comment by tamarpostma** [comment]
How about a PayPal donation button on the site? 
Then it’s sort of non-mandatory…
In another galaxy far far away and long ago, I was once a (very bad) java programmer  but loved solving problems like these, so I can see how this is a nice hobby to have.

Two-way would be fantastic if that could happen. Are the private/personal appointments part of the MbSepcial calendar?

**Comment by 7kasper** [comment]
Hi Tamar!

We are finished migrating the old users, you do need to reclaim your account following the same procedure.

Yes, indeed personal appointments are seen as special and put in that or the full calendar.
We have added a donation button like you suggested. This project is indeed a hobby and I think we have already learned a lot by programming it but also running a service that others depend on. (Partly because of your help :smile: ) We might do a two way sync in the future as it should be possible. Currently we operated under the assumption that most people like to replace magister with their google calendar :laughing: .

Thanks again,
Kasper & Sjoerd

**Comment by tamarpostma** [comment]
Dag Kasper & Sjoerd,

Just checked it out. Looking great! Is it already active? I activated again but not sure if it was too soon. 
How do I get my class names to show up ? Is this still possible in the single calendar or only the multiple ones?
Does the inlog link mean I can change previous settings?

I hope a 2-way is a future possibility. It would be so cool to make a personal appointment in google and have it show up in Magister as well as the other way around. That way you always have everything handy. It would just be nice to edit wherever and have it always be updated.
I had a meeting recently at school with Magister, they are building a new system called magister.me and say they want to implement an integrated calendar in the future too. Maybe you guys can get together?!? 

I also told my students about you today so you might be getting a bit more activity on the server soon.😎

Have fun! 
Tamar

Verstuurd vanaf mijn iPhone

**Comment by Sj3rd** [comment]
Hi Tamar,


Yes, the login page is alsof the update page. If you want toen change your preferences, just refill your credentials and tweak some settings.

Getting the classname is possible by clicking on "Meer opties", and then deselect the "Laat even versimpelde versie van he afspraak zien..." option, what will activate the class etc.

I (maybe @7kasper joins) will start working on the 2-way sync.

Lol, Magister hates us, people using the API (of which it is not intended that anyone would use it). So I don't think they see an cooperation possible, but we may want to reach out.

Thanks for sharing, please don't get more than 5000 people cause our system can't handle that haha.

Thanks for the donation 🙏, in total we got a full year of serverhosting donated so far, thanks!!


Kind regards,
Sjoerd

**Comment by tamarpostma** [comment]
Ok, all clear. Thanks for the update. 

Oeps. so maybe not mention you to Magister 😜…
They have an API? That IS surprising. 
2-way sync so soon!! Yes!! I will be your prime beta-tester. Tell me what to do. 😅

**Comment by Sj3rd** [comment]
Yes there's an API, but is forbidden for third parties to use... I think they don't hate us specifically, mainly because we're very careful with saving, encrypting etc of the sensitive information. But more the people who do bad stuff with it. I hope they'll bring API key access soon.

So you got a meeting with Magister?

**Comment by Sj3rd** [comment]
@tamarpostma wat is je schoolnaam/gebruikersnaam? Dan kan ik even Prime activeren :)

**Comment by tamarpostma** [comment]
Hi again!
That sounds interesting..
What is prime?! As in Prime user? 😎
Schoolname:  Groevenbeek (groevenbeek.magister.net)
Username: pmt

Verstuurd vanaf mijn iPhone

**Comment by tamarpostma** [comment]
Ah yes, Magister is extremely careful. Probably out of fear of losing the monopoly they have on LVS in the Netherlands.
They probably know once they are exposed everyone will beat them to it..
Yes. Actually, I meet with them now again because of their new product Magister.me which is still in infancy.

Verstuurd vanaf mijn iPhone

**Comment by tamarpostma** [comment]
Deleted it all again so we can start fresh..

Verstuurd vanaf mijn iPhone

**Comment by tamarpostma** [comment]
Yes! All is well...

**Comment by 7kasper** [comment]
Tamar, I have a few questions if you don't mind 😄 
Since you have a teacher account and I had another teacher interested in magbot but had his questions about savety. So I am curious to the workings of the teacher account. If you're at home can you access all functions? Can you add homework to lessons and grade pupils at home too? Or do you need some sort of special code to access the 'secure' parts etc?

Greetings.

**Comment by tamarpostma** [comment]
Yes, I can. We have a different setup than the kids. The parents see the same as the kids.
I can send you a screenshot if you want.
We can do everything at home and at school via web app. iOS is pretty limited though there is a new one in development.

Verstuurd vanaf mijn iPhone

**Comment by tamarpostma** [comment]
Are you getting my email? I keep getting an error. Maybe it’s too big..
Verstuurd vanaf mijn iPhone

**Comment by 7kasper** [comment]
We haven't gotten any email. Can you try sending it again or via wetransfer to info@magbot.nl ?

**Comment by tamarpostma** [comment]
Ok! Just sent it again

**Comment by tamarpostma** [comment]
Did you get anything?
I sent 3 screencasts. I think it was too big.
If you still didn’t get it I will weTransfer you!

Verstuurd vanaf mijn iPhone

**Comment by 7kasper** [comment]
Sorry I didn't answer yet, I didn't receive anything in the mail...

**Comment by tamarpostma** [comment]
Hi Kasper, (the email without the attachments, they have been sent in WeTransfer!)
Here are some screencasts. First one is my account.  You get a tour and then I made a personal appointment with a student (my son). Second one is also my account, where I show you the section where I can add homework and tests.
The second is the student account. Another tour and you can see the personal appointment I made.

All are via the browser. The students have an app too. We do too but it's crap.

This is a private message right?😎
